# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     env_file:
#       - ./backend/.env
#     expose:
#       - "8080"
#     networks:
#       - app-network

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile.frontend
#     container_name: frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge


version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: unless-stopped
