# name: Build and Push to ECR

# on:
#   push:
#     branches:
#       - main

# env:
#   VERSION_LABEL: v-${{ github.run_number }}
#   IMAGE_NAME: ${{ secrets.ECR_REPOSITORY }}
#   IMAGE_TAG: latest

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout source
#       uses: actions/checkout@v4

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Login to Amazon ECR
#       uses: aws-actions/amazon-ecr-login@v2

#     - name: Build and push Docker image
#       run: |
#         docker build -t $IMAGE_NAME:$IMAGE_TAG .
#         docker push $IMAGE_NAME:$IMAGE_TAG


name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  VERSION_LABEL: v-${{ github.run_number }}
  IMAGE_NAME: ${{ secrets.ECR_REPOSITORY }}
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build image using Docker Compose
      run: |
        docker-compose build

    - name: Tag image for ECR
      run: |
        docker tag wk5-gallery-app-app:latest $IMAGE_NAME:$IMAGE_TAG

    - name: Push image to ECR
      run: |
        docker push $IMAGE_NAME:$IMAGE_TAG
