name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.ECR_REPOSITORY }}
  VERSION_LABEL: v-${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME .

    - name: Tag Docker image
      run: |
        docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Push to ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/$IMAGE_NAME:latest
